%% run_ur5_pick_place_dynamics_control.m
% UR5 full nonlinear dynamics simulation for a pick-and-place task.
%
% This script:
%   1. Builds a Cartesian pick-and-place task.
%   2. Uses utils/inverse_kinematics.m to generate a desired joint trajectory.
%   3. Simulates the full nonlinear UR5 dynamics using UR5_fdyn.
%   4. Applies a computed-torque / feedback-linearization tracking controller.
%   5. Adds an optional payload load while the object is being carried.
%   6. Plots tracking errors and control torques.
%   7. Animates the actual dynamic response and saves an MP4 video.
%
% Required repository files:
%   UR5_params.m
%   maple_gen/UR5_M.m
%   maple_gen/UR5_h.m
%   maple_gen/UR5_G.m
%   maple_gen/UR5_fdyn.m
%   maple_gen/UR5_fkine.m
%   maple_gen/UR5_fkall.m
%   maple_gen/UR5_jacobian_geometric.m
%   utils/inverse_kinematics.m


clear; clc; close all;

%% Paths

addpath('maple_gen');
addpath('utils');

assert(exist('UR5_params','file') == 2, 'UR5_params.m not found.');
assert(exist('UR5_M','file') == 2, 'UR5_M.m not found.');
assert(exist('UR5_h','file') == 2, 'UR5_h.m not found.');
assert(exist('UR5_G','file') == 2, 'UR5_G.m not found.');
assert(exist('UR5_fdyn','file') == 2, 'UR5_fdyn.m not found.');
assert(exist('UR5_fkine','file') == 2, 'UR5_fkine.m not found.');
assert(exist('UR5_fkall','file') == 2, 'UR5_fkall.m not found.');
assert(exist('UR5_jacobian_geometric','file') == 2, 'UR5_jacobian_geometric.m not found.');
assert(exist('inverse_kinematics','file') == 2, 'utils/inverse_kinematics.m not found.');

USE_FIG_HELPERS = (exist('figureoptscall','file') == 2) && ...
                  (exist('saveFigureAsPDF','file') == 2);

if USE_FIG_HELPERS
    figureoptscall;
end

%% Load UR5 parameters
[~, Pi] = UR5_params();
n = 6;

%% Output settings
outdir = 'ur5_pick_place_dynamics_results';
if ~exist(outdir, 'dir')
    mkdir(outdir);
end

videoFile = fullfile(outdir, 'ur5_pick_place_dynamics_control.mp4');
fps = 30;

%% IK settings for generating the reference trajectory
ikOpts = struct();
ikOpts.maxIter = 120;
ikOpts.positionTolerance = 2e-4;
ikOpts.lambda = 0.035;
ikOpts.alpha = 0.9;
ikOpts.maxStep = deg2rad(4);
ikOpts.useOrientation = false;

%% Dynamic simulation and controller settings
% Computed-torque controller:
%   tau_motor = M(q)*(ddq_d + Kd*(dq_d-dq) + Kp*(q_d-q)) + h(q,dq) + G(q)

Kp = diag([95, 95, 75, 55, 35, 25]);
Kd = diag([22, 22, 18, 14, 10, 8]);

useTorqueLimits = false;
tauLimit = [180; 180; 140; 90; 70; 50];   % Nm, used only if useTorqueLimits = true

% Optional object payload during the carry phase.
% If payload.compensate = true, the controller cancels the known payload
% force, so computed-torque tracking should remain close to exact.
% If payload.compensate = false, the payload acts as an unmodeled
% disturbance and a small tracking offset can appear during carrying.
payload.enable = true;
payload.compensate = true;
payload.mass = 0.35;          % kg
payload.gravity = 9.81;       % m/s^2

odeOpts = odeset( ...
    'RelTol', 1e-6, ...
    'AbsTol', 1e-8, ...
    'MaxStep', 1/(5*fps));

%% Define reachable task locations from known UR5 configurations
% These seed configurations define reachable Cartesian pick/place points.
% The actual reference trajectory is generated by numerical IK.

qHome = deg2rad([  30;  -80;  105; -115;  -90;    0]);
qPickSeed = deg2rad([  45;  -95;  115; -110;  -90;   20]);
qPlaceSeed = deg2rad([ -35;  -80;  105; -115;  -90;  -20]);

THome = UR5_fkine(qHome, Pi);
TPick = UR5_fkine(qPickSeed, Pi);
TPlace = UR5_fkine(qPlaceSeed, Pi);

pHome = THome(1:3,4);
pPick = TPick(1:3,4);
pPlace = TPlace(1:3,4);

liftHeight = 0.14;
pPickAbove = pPick + [0; 0; liftHeight];
pPlaceAbove = pPlace + [0; 0; liftHeight];

%% Build smooth Cartesian task trajectory
% Object modes:
%   0 = object waiting at pick location
%   1 = object attached to the end-effector
%   2 = object placed at final location

segments = {
    pHome,       pPickAbove,   50, 0, 'Move above object';
    pPickAbove,  pPick,        30, 0, 'Lower to grasp';
    pPick,       pPickAbove,   35, 1, 'Lift object';
    pPickAbove,  pPlaceAbove,  65, 1, 'Carry object';
    pPlaceAbove, pPlace,       30, 1, 'Lower to place';
    pPlace,      pPlaceAbove,  35, 2, 'Release object';
    pPlaceAbove, pHome,        50, 2, 'Return home'
};

pDes = [];
objectMode = [];
phaseIndex = [];
phaseNames = strings(size(segments,1),1);

for i = 1:size(segments,1)
    pA = segments{i,1};
    pB = segments{i,2};
    nFrames = segments{i,3};
    mode = segments{i,4};
    phaseNames(i) = string(segments{i,5});

    pts = smoothCartesianSegment(pA, pB, nFrames);

    if i > 1
        pts = pts(:,2:end); % Avoid duplicate frames at segment boundaries.
    end

    pDes = [pDes, pts]; %#ok<AGROW>
    objectMode = [objectMode, mode*ones(1,size(pts,2))]; %#ok<AGROW>
    phaseIndex = [phaseIndex, i*ones(1,size(pts,2))]; %#ok<AGROW>
end

nRef = size(pDes,2);
dtRef = 1/fps;
tRef = (0:nRef-1)*dtRef;
Tf = tRef(end);

%% Generate desired joint trajectory using numerical IK
Qref = zeros(n,nRef);
ikPositionError = zeros(1,nRef);
ikConverged = false(1,nRef);

qPrev = qHome;

fprintf('Generating IK reference for %d frames...\n', nRef);

for k = 1:nRef
    [qSol, info] = inverse_kinematics(pDes(:,k), qPrev, Pi, ikOpts);

    Qref(:,k) = qSol;
    qPrev = qSol;

    ikPositionError(k) = info.positionErrorNorm;
    ikConverged(k) = info.converged;
end

DQref = numericalDerivative(Qref, dtRef);
DDQref = numericalDerivative(DQref, dtRef);

fprintf('IK reference generated.\n');
fprintf('Maximum IK position error: %.6f m\n', max(ikPositionError));
fprintf('Mean IK position error   : %.6f m\n', mean(ikPositionError));
fprintf('Converged IK frames      : %d / %d\n', nnz(ikConverged), nRef);

%% Simulate full nonlinear dynamics
% Use exact initial conditions by default so the computed-torque controller
% demonstrates near-exact tracking for the nominal model.
%
% Set initialMismatch.enable = true if you want to intentionally show the
% transient response from a nonzero initial tracking error.

initialMismatch.enable = false;
initialMismatch.offset = deg2rad([2; -2; 1.5; -1; 1; 0.5]);

if initialMismatch.enable
    q0 = Qref(:,1) + initialMismatch.offset;
else
    q0 = Qref(:,1);
end

dq0 = DQref(:,1);
x0 = [q0; dq0];

dynData = struct();
dynData.Pi = Pi;
dynData.tRef = tRef;
dynData.Qref = Qref;
dynData.DQref = DQref;
dynData.DDQref = DDQref;
dynData.objectMode = objectMode;
dynData.Kp = Kp;
dynData.Kd = Kd;
dynData.payload = payload;
dynData.initialMismatch = initialMismatch;
dynData.useTorqueLimits = useTorqueLimits;
dynData.tauLimit = tauLimit;

fprintf('Simulating full nonlinear dynamics with computed-torque control...\n');

rhs = @(t,x) closedLoopDynamics(t, x, dynData);

% Passing tRef as the time vector returns the solution sampled exactly at
% the animation/reference frames.
[tSim, xSim] = ode45(rhs, tRef, x0, odeOpts);

fprintf('Dynamic simulation completed.\n');

%% Post-process simulation
sim = postprocessDynamics(tSim, xSim, dynData);

fprintf('Maximum joint tracking error: %.6f rad\n', max(sim.errNorm));
fprintf('Mean joint tracking error   : %.6f rad\n', mean(sim.errNorm));
fprintf('Peak motor torque norm      : %.6f Nm\n', max(sim.tauMotorNorm));
fprintf('Payload enabled             : %d\n', payload.enable);
fprintf('Payload compensated         : %d\n', payload.compensate);

save(fullfile(outdir, 'ur5_pick_place_dynamics_results.mat'), ...
    'sim', 'dynData', 'pDes', 'pPick', 'pPlace', 'pPickAbove', 'pPlaceAbove', ...
    'phaseIndex', 'phaseNames', 'ikPositionError', 'ikConverged');

%% Plot tracking results
fig1 = figure('Color','w', 'Name', 'UR5 Dynamics Tracking Summary', ...
    'Position', [100 100 1000 800]);

tl = tiledlayout(fig1, 2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

ax1 = nexttile(tl);
plot(ax1, sim.t, sim.errNorm, 'LineWidth', 1.6);
grid(ax1, 'on');
xlabel(ax1, 'Time [s]');
ylabel(ax1, '$\|q_d - q\|_2$ [rad]');
%title(ax1, 'Joint-Space Tracking Error');

ax2 = nexttile(tl);
plot(ax2, sim.t, sim.tauMotorNorm, 'LineWidth', 1.6);
grid(ax2, 'on');
xlabel(ax2, 'Time [s]');
ylabel(ax2, '$\|\tau_{motor}\|_2$ [Nm]');
%title(ax2, 'Motor Torque Norm');

% ax3 = nexttile(tl);
% plot(ax3, sim.eeDesired(1,:), sim.eeDesired(2,:), '--', 'LineWidth', 1.2); hold(ax3, 'on');
% plot(ax3, sim.eeActual(1,:), sim.eeActual(2,:), 'LineWidth', 1.6);
% grid(ax3, 'on'); axis(ax3, 'equal');
% xlabel(ax3, '$X$ [m]');
% ylabel(ax3, '$Y$ [m]');
% legend(ax3, 'Desired EE path', 'Actual EE path', 'Location', 'best');
% title(ax3, 'End-Effector Path Projection');

if USE_FIG_HELPERS
    saveFigureAsPDF(fig1, fullfile(outdir, 'fig_tracking_summary.pdf'));
else
    saveas(fig1, fullfile(outdir, 'fig_tracking_summary.png'));
end

fig2 = figure('Color','w', 'Name', 'UR5 Joint Tracking', ...
    'Position', [120 120 1100 850]);

tl2 = tiledlayout(fig2, 3, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

for j = 1:n
    ax = nexttile(tl2);
    plot(ax, sim.t, sim.Qref(j,:), '--', 'LineWidth', 1.1); hold(ax, 'on');
    plot(ax, sim.t, sim.Q(j,:), 'LineWidth', 1.4);
    grid(ax, 'on');
    xlabel(ax, 'Time [s]');
    ylabel(ax, sprintf('$q_%d$ [rad]', j));
    %title(ax, sprintf('Joint %d', j));
    if j == 1
        legend(ax, 'Desired', 'Actual', 'Location', 'best');
    end
end

if USE_FIG_HELPERS
    saveFigureAsPDF(fig2, fullfile(outdir, 'fig_joint_tracking.pdf'));
else
    saveas(fig2, fullfile(outdir, 'fig_joint_tracking.png'));
end

fig3 = figure('Color','w', 'Name', 'UR5 Motor Torques', ...
    'Position', [140 140 1100 850]);

tl3 = tiledlayout(fig3, 3, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

for j = 1:n
    ax = nexttile(tl3);
    plot(ax, sim.t, sim.tauMotor(j,:), 'LineWidth', 1.4);
    grid(ax, 'on');
    xlabel(ax, 'Time [s]');
    ylabel(ax, sprintf('$\\tau_%d$ [Nm]', j));
    %title(ax, sprintf('Motor Torque %d', j));
end

if USE_FIG_HELPERS
    saveFigureAsPDF(fig3, fullfile(outdir, 'fig_motor_torques.pdf'));
else
    saveas(fig3, fullfile(outdir, 'fig_motor_torques.png'));
end

%% Pre-compute link positions for animation
linkPositions = zeros(3,7,nRef);
TeeAll = zeros(4,4,nRef);

for k = 1:nRef
    [Tlist, Tee] = UR5_fkall(sim.Q(:,k), Pi);
    TeeAll(:,:,k) = Tee;

    for j = 1:7
        linkPositions(:,j,k) = Tlist{j}(1:3,4);
    end
end

allPts = reshape(linkPositions, 3, []);
allPts = [allPts, pDes, sim.eeActual, sim.eeDesired, pPick, pPlace, pPickAbove, pPlaceAbove]; %#ok<AGROW>

padding = 0.18;
xyzMin = min(allPts, [], 2) - padding;
xyzMax = max(allPts, [], 2) + padding;

xyzMin(3) = min(xyzMin(3), -0.02);
xyzMax(3) = max(xyzMax(3), 0.65);

%% Prepare video writer
try
    writerObj = VideoWriter(videoFile, 'MPEG-4');
catch
    videoFile = fullfile(outdir, 'ur5_pick_place_dynamics_control.avi');
    writerObj = VideoWriter(videoFile, 'Motion JPEG AVI');
end

writerObj.FrameRate = fps;
open(writerObj);

%% Animate actual dynamic response and save video
figAnim = figure('Color', 'w', 'Position', [100 100 1200 800]);

cubeSide = 0.06;
cubePickCenter = pPick - [0; 0; cubeSide/2];
cubePlaceCenter = pPlace - [0; 0; cubeSide/2];

fprintf('Writing dynamics video: %s\n', videoFile);

for k = 1:nRef
    clf(figAnim);
    hold on; grid on; axis equal;

    xlabel('$X$ [m]');
    ylabel('$Y$ [m]');
    zlabel('$Z$ [m]');

    xlim([xyzMin(1), xyzMax(1)]);
    ylim([xyzMin(2), xyzMax(2)]);
    zlim([xyzMin(3), xyzMax(3)]);

    view(170, 25);
    set(gca, 'FontSize', 11);

    drawFloor(xyzMin, xyzMax);

    % Desired and actual end-effector paths
    plot3(sim.eeDesired(1,:), sim.eeDesired(2,:), sim.eeDesired(3,:), '--', ...
        'Color', [0.65 0.65 0.65], 'LineWidth', 1.0);
    plot3(sim.eeActual(1,1:k), sim.eeActual(2,1:k), sim.eeActual(3,1:k), ...
        'Color', [0.0 0.45 0.74], 'LineWidth', 2.0);

    % Pick and place markers
    plot3(pPick(1), pPick(2), pPick(3), 'o', ...
        'MarkerSize', 8, 'MarkerFaceColor', [0.47 0.67 0.19], ...
        'MarkerEdgeColor', 'k');
    plot3(pPlace(1), pPlace(2), pPlace(3), 's', ...
        'MarkerSize', 8, 'MarkerFaceColor', [0.85 0.33 0.10], ...
        'MarkerEdgeColor', 'k');

    % Object state follows the actual dynamic end-effector when carried.
    if objectMode(k) == 0
        cubeCenter = cubePickCenter;
    elseif objectMode(k) == 1
        pe = TeeAll(1:3,4,k);
        cubeCenter = pe - [0; 0; cubeSide/2];
    else
        cubeCenter = cubePlaceCenter;
    end

    drawCube(cubeCenter, cubeSide, [1.0 0.8 0.2], 0.95);

    % Robot and gripper
    currentLinks = linkPositions(:,:,k);
    drawRobot(currentLinks);
    drawGripper(TeeAll(:,:,k), objectMode(k) == 1);

    phaseText = char(phaseNames(phaseIndex(k)));
    title(sprintf('UR5 Full Dynamics + Computed-Torque Control | %s | Frame %d/%d', ...
        phaseText, k, nRef), 'Interpreter', 'none');

    drawnow;
    writeVideo(writerObj, getframe(figAnim));
end

close(writerObj);

fprintf('Done.\n');
fprintf('Results folder:\n%s\n', outdir);
fprintf('Video saved to:\n%s\n', videoFile);

%% Local helper functions

function dx = closedLoopDynamics(t, x, data)
%CLOSEDLOOPDYNAMICS Full nonlinear UR5 dynamics under computed-torque control.

    q = x(1:6);
    dq = x(7:12);

    [qd, dqd, ddqd, mode] = referenceAtTime(t, data);

    e = qd - q;
    de = dqd - dq;

    v = ddqd + data.Kd*de + data.Kp*e;

    tauPayload = payloadGeneralizedTorque(q, mode, data);

    % Nominal computed-torque command for:
    %   M(q)*qdd + h(q,dq) + G(q) = tau
    tauNominal = UR5_M(q, data.Pi)*v + UR5_h(q, dq, data.Pi) + UR5_G(q, data.Pi);

    if data.payload.enable && data.payload.compensate
        % The plant receives tauMotor + tauPayload. Subtracting tauPayload
        % from the commanded motor torque cancels the known payload load.
        tauMotor = tauNominal - tauPayload;
    else
        % Payload, if enabled, remains as an external disturbance.
        tauMotor = tauNominal;
    end

    if data.useTorqueLimits
        tauMotor = min(max(tauMotor, -data.tauLimit), data.tauLimit);
    end

    % The plant sees motor torque plus external generalized torque.
    qdd = UR5_fdyn(q, dq, tauMotor + tauPayload, data.Pi);

    dx = [dq; qdd];
end

function sim = postprocessDynamics(tSim, xSim, data)
%POSTPROCESSDYNAMICS Evaluate references, errors, torques, and EE paths.

    t = tSim(:).';
    nT = numel(t);

    Q = xSim(:,1:6).';
    DQ = xSim(:,7:12).';

    Qref = zeros(6,nT);
    DQref = zeros(6,nT);
    DDQref = zeros(6,nT);
    err = zeros(6,nT);
    derr = zeros(6,nT);
    tauMotor = zeros(6,nT);
    tauPayload = zeros(6,nT);
    tauTotal = zeros(6,nT);
    modes = zeros(1,nT);
    eeActual = zeros(3,nT);
    eeDesired = zeros(3,nT);

    for k = 1:nT
        q = Q(:,k);
        dq = DQ(:,k);

        [qd, dqd, ddqd, mode] = referenceAtTime(t(k), data);

        e = qd - q;
        de = dqd - dq;

        v = ddqd + data.Kd*de + data.Kp*e;

        tauP = payloadGeneralizedTorque(q, mode, data);

        tauNominal = UR5_M(q, data.Pi)*v + UR5_h(q, dq, data.Pi) + UR5_G(q, data.Pi);

        if data.payload.enable && data.payload.compensate
            tauM = tauNominal - tauP;
        else
            tauM = tauNominal;
        end

        if data.useTorqueLimits
            tauM = min(max(tauM, -data.tauLimit), data.tauLimit);
        end

        Tactual = UR5_fkine(q, data.Pi);
        Tdesired = UR5_fkine(qd, data.Pi);

        Qref(:,k) = qd;
        DQref(:,k) = dqd;
        DDQref(:,k) = ddqd;
        err(:,k) = e;
        derr(:,k) = de;
        tauMotor(:,k) = tauM;
        tauPayload(:,k) = tauP;
        tauTotal(:,k) = tauM + tauP;
        modes(k) = mode;
        eeActual(:,k) = Tactual(1:3,4);
        eeDesired(:,k) = Tdesired(1:3,4);
    end

    sim = struct();
    sim.t = t;
    sim.Q = Q;
    sim.DQ = DQ;
    sim.Qref = Qref;
    sim.DQref = DQref;
    sim.DDQref = DDQref;
    sim.err = err;
    sim.derr = derr;
    sim.errNorm = vecnorm(err, 2, 1);
    sim.derrNorm = vecnorm(derr, 2, 1);
    sim.tauMotor = tauMotor;
    sim.tauPayload = tauPayload;
    sim.tauTotal = tauTotal;
    sim.tauMotorNorm = vecnorm(tauMotor, 2, 1);
    sim.tauPayloadNorm = vecnorm(tauPayload, 2, 1);
    sim.tauTotalNorm = vecnorm(tauTotal, 2, 1);
    sim.objectMode = modes;
    sim.eeActual = eeActual;
    sim.eeDesired = eeDesired;
end

function [qd, dqd, ddqd, mode] = referenceAtTime(t, data)
%REFERENCEATTIME Interpolate desired joint trajectory and object mode.

    tq = min(max(t, data.tRef(1)), data.tRef(end));

    qd = interp1(data.tRef, data.Qref.', tq, 'pchip').';
    dqd = interp1(data.tRef, data.DQref.', tq, 'pchip').';
    ddqd = interp1(data.tRef, data.DDQref.', tq, 'pchip').';

    mode = interp1(data.tRef, data.objectMode(:), tq, 'nearest', 'extrap');
end

function tauPayload = payloadGeneralizedTorque(q, mode, data)
%PAYLOADGENERALIZEDTORQUE Map payload weight to joint generalized torque.

    tauPayload = zeros(6,1);

    if ~data.payload.enable || mode ~= 1
        return;
    end

    [~, ~, Jg] = UR5_jacobian_geometric(q, data.Pi);
    Jv = Jg(1:3,:);

    Fpayload = [0; 0; -data.payload.mass * data.payload.gravity];

    tauPayload = Jv.' * Fpayload;
end

function dY = numericalDerivative(Y, dt)
%NUMERICALDERIVATIVE Central finite-difference derivative for row signals.

    dY = zeros(size(Y));

    dY(:,1) = (Y(:,2) - Y(:,1)) / dt;
    dY(:,end) = (Y(:,end) - Y(:,end-1)) / dt;

    if size(Y,2) > 2
        dY(:,2:end-1) = (Y(:,3:end) - Y(:,1:end-2)) / (2*dt);
    end
end

function pts = smoothCartesianSegment(pA, pB, nFrames)
%SMOOTHCARTESIANSEGMENT Quintic time-scaling between two 3D points.

    tau = linspace(0, 1, nFrames);
    s = 10*tau.^3 - 15*tau.^4 + 6*tau.^5;
    pts = pA(:) + (pB(:) - pA(:)) .* s;
end

function drawRobot(P)
%DRAWROBOT Draw UR5 link chain from precomputed frame origins.

    plot3(P(1,:), P(2,:), P(3,:), '-o', ...
        'LineWidth', 4.0, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', [0.1 0.1 0.1], ...
        'MarkerEdgeColor', 'k', ...
        'Color', [0.0 0.25 0.70]);

    plot3(P(1,1), P(2,1), P(3,1), 's', ...
        'MarkerSize', 12, ...
        'MarkerFaceColor', [0.2 0.2 0.2], ...
        'MarkerEdgeColor', 'k');
end

function drawGripper(Tee, isClosed)
%DRAWGRIPPER Draw a simple two-finger gripper at the end-effector frame.

    R = Tee(1:3,1:3);
    p = Tee(1:3,4);

    if isClosed
        jawWidth = 0.028;
    else
        jawWidth = 0.075;
    end

    fingerLength = 0.07;

    sideAxis = R(:,2);
    approachAxis = -R(:,3);

    base1 = p + 0.5*jawWidth*sideAxis;
    base2 = p - 0.5*jawWidth*sideAxis;

    tip1 = base1 + fingerLength*approachAxis;
    tip2 = base2 + fingerLength*approachAxis;

    plot3([base1(1) tip1(1)], [base1(2) tip1(2)], [base1(3) tip1(3)], ...
        'k-', 'LineWidth', 3.0);
    plot3([base2(1) tip2(1)], [base2(2) tip2(2)], [base2(3) tip2(3)], ...
        'k-', 'LineWidth', 3.0);

    plot3([base1(1) base2(1)], [base1(2) base2(2)], [base1(3) base2(3)], ...
        'k-', 'LineWidth', 2.0);

    plot3(p(1), p(2), p(3), 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 5);
end

function drawCube(center, sideLength, faceColor, faceAlpha)
%DRAWCUBE Draw a cube centered at center.

    c = center(:).';
    s = sideLength/2;

    vertices = [
        -s -s -s;
         s -s -s;
         s  s -s;
        -s  s -s;
        -s -s  s;
         s -s  s;
         s  s  s;
        -s  s  s] + c;

    faces = [
        1 2 3 4;
        5 6 7 8;
        1 2 6 5;
        2 3 7 6;
        3 4 8 7;
        4 1 5 8];

    patch('Vertices', vertices, ...
          'Faces', faces, ...
          'FaceColor', faceColor, ...
          'FaceAlpha', faceAlpha, ...
          'EdgeColor', 'k', ...
          'LineWidth', 1.0);
end

function drawFloor(xyzMin, xyzMax)
%DRAWFLOOR Draw a simple ground plane at z = 0.

    x1 = xyzMin(1);
    x2 = xyzMax(1);
    y1 = xyzMin(2);
    y2 = xyzMax(2);

    floorVertices = [
        x1 y1 0;
        x2 y1 0;
        x2 y2 0;
        x1 y2 0];

    floorFaces = [1 2 3 4];

    patch('Vertices', floorVertices, ...
          'Faces', floorFaces, ...
          'FaceColor', [0.93 0.93 0.93], ...
          'FaceAlpha', 0.35, ...
          'EdgeColor', [0.75 0.75 0.75]);
end
